import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Sharing",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: imprimante1,
    productName: "imprimante",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "202",
    img: imprimante2,
    productName: "imprimante",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "203",
    img: imprimante4,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "204",
    img: imprimante5,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "205",
    img: imprimante6,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "206",
    img: imprimante7,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "207",
    img: imprimante8,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "208",
    img: imprimante9,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "209",
    img: encre1,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "210",
    img: encre2,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "211",
    img: encre3,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "212",
    img: encre4,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "217",
    img: bac1,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "220",
    img: bac3,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "EIGER STREAMLINE 45 CARRIER",
    price: "30.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Carrier Streamline 45 dirancang untuk kegiatan hiking selama 1-3 hari. Carrier yang berkapasitas 45 Liter ini dilengkapi dengan fitur backsystem Fit Light yang dapat memberikan kenyamanan dan meminimalisir panas pada punggung Anda. Selain itu, terdapat 2 saku praktis pada bagian atas dan samping carrier untuk memudahkan Anda menyimpan dan mengakses barang-barang yang dibutuhkan dengan cepat. Fitur tambahan lainnya seperti tali dada, pengikat trekking pole, tali kompresi samping, dan tali pinggang, menjadikan carrier Streamline 45 ini sebagai pilihan yang cocok untuk menemani kegiatan hiking Anda",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Teknologi backsystem Fit Light." },
      { label: "Dimension ", value: "30 x 22 x 67 cm" },

      { label: "Material ", value: "Polyester 600D       " },
      { label: "Load Range", value: "3-8kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },
  {
    _id: "202",
    img: IMPRIMANTE_PANTUM_BM5100FDW,
    productName: "EIGER HIKEOVER 45 CORDURA 1.0 CARRIER",
    price: "35.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Hikehover 45 Cordura 1.0 adalah carrier berkapasitas 45 liter yang dirancang untuk menemani kegiatan hiking Anda (1-2 hari). Tas ini menggunakan bahan Cordura yang ringan dan memiliki performa ketahanan yang kuat. Backpack ini dilengkapi dengan teknologi backsystem Aerovent Light yang memaksimalkan aliran udara dan meminimalkan kontak langsung dengan punggung untuk kenyamanan Anda saat membawa beban. Memiliki bobot sangat ringan, tas ini dapat diandalkan untuk membawa beban hingga 10 kg. Hikehover 45 Cordura 1.0 memiliki banyak tempat penyimpanan, diantaranya kompartemen utama, saku tutup atas, saku sisip depan, saku samping, dan saku hip belt untuk menjaga barang bawaan Anda terorganisir dan mudah diakses. ",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Teknologi backsystem Aerovent Light." },
      { label: "Dimension ", value: "30 x 24 x 65 cm" },

      { label: "Material ", value: "Nylon 400D Cordura Ripstop       " },
      { label: "Load Range", value: "2-10 kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },

  {
    _id: "203",
    img: IMPRIMANTE_PANTUM_BP5100DN,
    productName: "EIGER STREAMLINE 35 WS CARRIER",
    price: "20.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Carrier Streamline 35 dirancang untuk kegiatan hiking selama 1-3 hari. Carrier yang berkapasitas 35 Liter ini dilengkapi dengan fitur backsystem Fit Light yang dapat memberikan kenyamanan dan meminimalisir panas pada punggung Anda. Selain itu, terdapat 2 saku praktis pada bagian atas dan samping carrier untuk memudahkan Anda menyimpan dan mengakses barang-barang yang dibutuhkan dengan cepat. Fitur tambahan lainnya seperti, tali dada, pengikat trekking pole, tali kompresi samping, dan tali pinggang, menjadikan carrier Streamline 35 ini sebagai pilihan yang cocok untuk menemani kegiatan hiking Anda.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Teknologi backsystem Fit Light." },
      { label: "Dimension ", value: "30 x 18 x 60 cm" },

      { label: "Material ", value: "Polyester 600D       " },
      { label: "Load Range", value: "2-6kg " },
      {
        label: "Gender ",
        value: "untuk Wanita ",
      },
    ],
  },
  {
    _id: "2005",
    img: IMPRIMANTE_PANTUM_M6609N,
    productName: "EIGER Z-STREAMLINE 45 CARRIER",
    price: "30.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Z-Streamline 45 adalah tas carrier berkapasitas 45lt. yang dirancang khusus untuk kegiatan hiking singkat, yakni 1-2 hari. Tas ini memiliki kompartemen utama dan kompartemen eksternal, seperti saku samping berbahan mesh dan saku tutup atas. Tas ini juga dilengkapi dengan FitLight Backsystem Technology yang berfungsi untuk memberikan sirkulasi udara yang baik dan kenyamanan bagi punggung saat membawa beban.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Teknologi backsystem dengan frame aluminium." },
      { label: "Dimension ", value: "30 x 22 x 67 cm" },

      { label: "Material ", value: "Polyester 600D       " },
      { label: "Load Range", value: "3-8kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },

  {
    _id: "20005",
    img: IMPRIMANTE_PANTUM_M6559N,
    productName: "EIGER EQUATOR 45 CARRIER",
    price: "35.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Equator 45 adalah tas carrier berkapasitas 45 liter yang dirancang untuk kegiatan trekking dan hiking selama 1-2 hari. Tas ini memiliki kompartemen utama dengan pemisah/sekat dan kompartemen eksternal, seperti saku samping, saku tutup atas, dan saku hip belt untuk menjaga barang bawaan Anda tetap aman dan terjaga. Tas ini juga dilengkapi dengan teknologi backsystem Aerovent Trek yang membuat sirkulasi udara di punggung Anda lebih optimal. Equator 45 juga memiliki fitur-fitur lain untuk mendukung perannya sebagai tas carrier ideal untuk perjalanan trekking Anda seperti pengikat trekking pole, kompartemen untuk menyimpan water bladder, tali kompresi samping, dan rain cover untuk melindungi tas dari air hujan.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Aerovent Trek adalah teknologi backsystem yang efektif meminimalisir keringat berlebih pada punggung dengan menyediakan ruang lebih untuk sirkulasi udara." },
      { label: "Dimension ", value: "35 x 31 x 60 cm" },

      { label: "Material ", value: "Polyester 600D       " },
      { label: "Load Range", value: "3-9kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },

  {
    _id: "206",
    img: IMPRIMANTE_PANTUM_P3300DN,
    productName: "EIGER ARDOR 45 LUNARIS WS 1.0 CARRIER",
    price: "30.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Memiliki bobot yang ringan dan berdaya tahan kuat, Ardor Lunaris WS 45 1.0 adalah carrier berkapasitas 45 liter yang dirancang untuk menemani kegiatan hiking Anda (1-2 hari). Guna memberikan kenyamanan saat membawa beban, tas ini didukung oleh tali bahu yang dirancang secara ergonomis agar pas dipakai mengikuti tubuh wanita dan teknologi backsystem Aerovent Light yang memaksimalkan aliran udara dan meminimalkan kontak langsung dengan punggung. Ardor Lunaris 45 memiliki banyak tempat penyimpanan, diantaranya kompartemen utama, saku tutup atas, saku depan, saku samping, dan saku hip belt untuk menjaga barang bawaan Anda terorganisir dan mudah diakses.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Teknologi backsystem Aerovent Light." },
      { label: "Dimension ", value: "30 x 22 x 68 cm" },

      { label: "Material ", value: "Nylon 420D Oxford       " },
      { label: "Load Range", value: "3-8kg " },
      {
        label: "Gender ",
        value: "untuk Wanita ",
      },
    ],
  },

  {
    _id: "207",
    img: IMPRIMANTE_PANTUM_P3300DW,
    productName: "EIGER EXCELSIOR 75+15L 2F CARRIER",
    price: "75.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Excelsior 75+15L 2F adalah tas carrier yang dirancang untuk kegiatan ekspedisi dan trekking berdurasi panjang (lebih dari 4 hari). Tas ini dilengkapi dengan teknologi backsystem Ergo Spino Dual Frame yang dapat membagi beban secara merata dan memiliki frame berpengatur ukuran torso yang dapat menjaga tulang belakang dari resiko cedera, serta ruang sirkulasi udara yang lebih luas. Penutup carrier dapat dilepas pasang dan dijadikan sebagai tas ransel mini.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Ergospino adalah backsystem berteknologi dual frame yang dapat menjaga tulang belakang dari resiko cedera pada saat Anda beraktivitas luar ruang." },
      { label: "Dimension ", value: "82 x 37 x 30 cm (Vol 75L+15L)" },

      { label: "Material ", value: "Polyester 600D, Nylon Robic Hexa 100       " },
      { label: "Load Range", value: "10-20kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },

  {
    _id: "208",
    img: IMPRIMANTE_PANTUM_P2509W,
    productName: "EIGER RHINOS 45 NG CARRIER",
    price: "30.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Rhinos 45 NG adalah carrier yang dirancang untuk kegiatan hiking selama 1-3 hari. Ransel berkapasitas 45 Liter ini dilengkapi dengan fitur backsystem Fit Light yang dapat memberikan kenyamanan dan meminimalisir panas pada punggung Anda. Tas ini memiliki kompartemen utama untuk menyimpan dan menjangkau peralatan Anda dengan leluasa. Terdapat saku samping untuk menyimpan botol minum dan saku hipbelt untuk memudahkan penyimpanan barang bawaan yang sering diakses. Fitur tambahan lainnya yang mendukung kegiatan hiking Anda, diantaranya fitur tali dada, pengikat trekking pole, dan tali kompresi, dan lubang hydration system. Terdapat pula rain cover untuk memastikan barang bawaan Anda terlindungi saat hujan.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Teknologi backsystem Fit Light." },
      { label: "Dimension ", value: "30 x 25 x 67 cm" },

      { label: "Material ", value: "Polyester 600D, Polyester 200D Recycled Lining      " },
      { label: "Load Range", value: "3-10kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },
  {
    _id: "233",
    img: IMPRIMANTE_PANTUM_P2509,
    productName: "EIGER Z-HYPERLITE SUMMIT 35 CARRIER",
    price: "25.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Z Hyperlite Summit 35 adalah backpack yang dirancang untuk kegiatan summit attack dan speed hiking. Tas ini memiliki kompartemen utamadan kompartemen eksternal, seperti saku samping, saku tutup atas, dan saku sisip depan untuk menyimpan perlengkapan. Tasberkapasitas 35 liter ini juga didukung juga dengan Fit Light Backsystem Technology yang dirancang ringan dan ringkas untuk kebutuhanpergerakan yang cepat, serta dilengkapi dengan wire frame steel kuat dan lentur sebagai konstruksi backsystem.. Terdapat pula rain coveruntuk memastikan barang bawaan Anda terlindungi saat terkena air hujan.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Fit Light adalah teknologi backsystem yang dirancang ringan dan ringkas untuk kebutuhan pergerakan yang cepat saat melakukan kegiatan summit attack (perjalanan penuntas menuju puncak)." },
      { label: "Dimension ", value: "28 x 20 x 66 cm" },

      { label: "Material ", value: "Polyester 150D, Nylon 420D       " },
      { label: "Load Range", value: "2-7kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },
  {
    _id: "220",
    img: bac3,
    productName: "AREI SLEEPING BAG EVEREST",
    price: "15.000",
    color: "1 hari",
    badge: true,
    brand: "Arei",
    des: "Kantong Tidur / Sleeping Bag Tikar Everest Arei Outdoorgear Cocok digunakan untuk beristirahat saat melakukan aktifitas Outdoor seperti Camping, Trekking, maupun aktifitas Outdoor lainnya.",
    cat: "Sleeping Bag",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Menjaga Badan Tetap Hangat saat Cuaca Dingin. Cocok digunakan untuk hiking, camping, travelling dan kegiatan outdoor lainnya" },
      { label: "Dimension ", value: "195 X 144 cm" },

      { label: "Material ", value: "Polyester Ripstop + Dacron       " },
      { label: "Weight", value: "715 gram " },
      {
        label: "Gender ",
        value: "untuk Pria & Wanita ",
      },
    ],
  },
  {
    _id: "221",
    img: bac4,
    productName: "CONSINA SLEEPING BAG SWEET DREAM",
    price: "15.000",
    color: "1 hari",
    badge: true,
    brand: "Consina",
    des: "Kantong Tidur / Sleeping Bag Consina Sweet Dream Cocok digunakan untuk beristirahat saat melakukan aktifitas Outdoor seperti Camping, Trekking, maupun aktifitas Outdoor lainnya.",
    cat: "Sleeping Bag",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Adjustable hoodie, Rubber straps packing, Lightweight" },
      { label: "Dimension ", value: "200 x 70 cm" },

      { label: "Material ", value: "Outer Nylon Polyester (Parasut) Windbreaker       " },
      { label: "Weight", value: "0.7 Kg " },
      {
        label: "Gender ",
        value: "untuk Pria & Wanita ",
      },
    ],
  },
  {
    _id: "215",
    img: ruban3,
    productName: "AREI MONTREAL BOOTS",
    price: "25.000",
    color: "1 hari",
    badge: true,
    brand: "Arei",
    des: "Produk ini Didesain Khusus Untuk Areingers Dengan Kualitas Terbaik, Brand Arei berawal dari sebuah pemikiran, ide dan mimpi serta keyakinan memberikan yang terbaik untuk alam dan negeri. Arei pun lahir menjadi sebuah kekuatan baru dalam industri tas khususnya tas untuk para penggiat alam. Di tahun 2005, Arei menginginkan sebuah produk yang sangat menunjang berbagai kegiatan para penggiat alam maupun yang berkegiatan di alam luar.",
    cat: "Sepatu",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Grip System pada bagian bagian outsole rubber memliki daya cengkram yang baik dan kuat untuk menjaga pijakan tetap stabil dan tidak licin, ringan, nyaman saat dipakai, dilengkapi double injection." },
      { label: "Size ", value: "38-45" },

      { label: "Material ", value: "Microfiber, Synthetic, Rubber Outsole    " },
      { label: "Weight", value: "465gr " },
      {
        label: "Gender ",
        value: "untuk Pria & Wanita ",
      },
    ],
  },
  {
    _id: "216",
    img: ruban4,
    productName: "EIGER POLLOCK 2.0 28 GUNUNG MID CUT SHOES",
    price: "35.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Sepatu Pollock 2.0 adalah salah satu dari rangkaian produk Ekspedisi 28 Gunung yang dirancang untuk kegiatan hiking. Gusset construction pada sepatu mid cut ini berfungsi untuk mencegah langsung masuknya air dari bagian atas sepatu. Sementara itu, teknologi heel support system dapat menyangga pergelangan kaki pada saat melakukan pendakian guna menunjang kaki agar tetap stabil. Sepatu ini juga didukung outsole Vibram untuk cengkraman yang lebih baik dan insole Ortholite yang memberikan bantalan, breathable (memiliki daya evaporasi tinggi yang mampu menguapkan kelembapan sehingga mudah kering), dan ringan untuk menjaga kaki tetap Nyaman.",
    cat: "Sepatu",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Teknologi heel support system, yang berfungsi untuk menyangga pergelangan kaki pada saat melakukan pendakian guna menunjang kaki agar tetap stabil di berbagai kondisi medan" },
      { label: "Size ", value: "38-45" },

      { label: "Material ", value: "Outsole Vibram Grivola, Insole Ortholite  " },
      { label: "Weight", value: "870 gram " },
      {
        label: "Gender ",
        value: "untuk Pria",
      },
    ],
  },
  {
    _id: "209",
    img: encre1,
    productName: "EIGER X-CASUARINA 6P TENT BLUE",
    price: "50.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Memilki desain yang cukup luas dan nyaman, tenda Casuarina 6P siap menemani petualangan berkemah Anda bersama teman dan keluarga. Ideal untuk kapasitas enam orang, tenda Casuarina 6P ini hadir dengan desain satu pintu masuk dan teras tenda memanjang yang menawarkan kemudahan untuk menyimpan peralatan Anda. Terbuat dari material waterproof polyester dengan konstruksi double-layer serta dilengkapi triangular rag, tenda Casuarina 6P ini menawarkan perlindungan yang tahan terhadap kondisi cuaca hujan ataupun berangin. Selain mudah dipasang dan multifungsi, tenda Casuarina 6P juga dilenkapi dengan breathable panel mesh yang memberikan ventilasi sekaligus menawarkan akses untuk menikmati pemandangan alam yang menakjubkan. Ketika selesai dipakai, Anda dapat menyimpannya kembali di carry bag.",
    cat: "Tenda",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Guyline reflektif membantu lebih mudah terlihat di malam hari atau saat keadaan minim cahaya." },
      { label: "Dimension ", value: "270 x (80+270) x 155cm" },

      { label: "Material ", value: "190T Polyester PU 2000mm       " },
      { label: "Weight", value: "4.6 kg " },
      {
        label: "Frame ",
        value: "Fiberglass 9.5mm ",
      },
    ],
  },
  {
    _id: "210",
    img: encre2,
    productName: "AREI TENDA LORENTZ 2P",
    price: "35.000",
    color: "1 hari",
    badge: true,
    brand: "Arei",
    des: "Tenda Camping Lorentz Kapasitas 2 Orang 03 IN 01 Arei Outdoorgear cocok digunakan untuk camping maupun aktifitas outdoor lainnya, dilengkapi dengan fitur double layer dan bahan waterproof yang membuat Areingers tidak perlu khawatir menghadapi cuaca hujan. Tenda Camping Lorentz Kapasitas 2 Orang 03 IN 01 Arei Outdoorgear siap menemani petualangan Areingers.",
    cat: "Tenda",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Tenda ini sudah Dilengkapi dengan Footprint, Extension, Vestibule dan Special Bag" },
      { label: "Dimension ", value: "210 X (70+140+70) x 105 cm" },

      { label: "Material ", value: "210T Ripstop Polyester PU 3000MM, UPF 50+, Seam Taped       " },
      { label: "Weight", value: "2350 gram " },
      {
        label: "Frame ",
        value: "Alumunium Poles 8,5 MM With Triangle Joining ",
      },
    ],
  },

  {
    _id: "211",
    img: encre3,
    productName: "EIGER NOVUS GUARDIAN 8P TENT",
    price: "75.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Setelah seharian menjelajahi alam Anda membutuhkan tempat beristirahat yang nyaman, dan Tenda Novus 8P dapat kamu andalkan. Tenda dengan desain luas yang berdaya tahan kuat serta memilki ketahanan air yang baik ini sangat mudah dipasang dan berkapasitas hingga delapan orang. Dilengkapi pintu utama, ventilasi, serta area vestibule luas yang dapat dijadikan sebagai tempat penyimpanan barang bawaan Anda. Tidak perlu khawatir saat pengemasan, Anda dapat menyimpannya dalam ke dalam carry bag dan membawanya kembali ke petualangan selanjutnya.",
    cat: "Tenda",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Terbuat dari material waterproof polyester, Jendela dengan bukaan ritsleting besar pada bagian inner tent, Dilengkapi akses dua pintu masuk dan area vestibule yang luas serta footprint" },
      { label: "Dimension ", value: "630 x 300 x 200cm" },

      { label: "Material ", value: "Polyester PU3000       " },
      { label: "Weight", value: "7 kg " },
      {
        label: "Frame ",
        value: "Steel ",
      },
    ],
  },
  {
    _id: "212",
    img: encre4,
    productName: "CONSINA PREMIUM UL DOME TENDA 2P",
    price: "30.000",
    color: "1 hari",
    badge: true,
    brand: "Consina",
    des: "Dengan berat hanya 1,6kg dan kapasitas 2 orang, Consina Ultra Light Dome dapat menjadi andalan mu saat bertualang bersama sahabat. Design tangguh untuk dicuaca ekstrem, sangat ringan dan simpel untuk dibawa, mudan didirikan, dengan bahan nylon dan coating silicon, membuat tenda sangat ringan dan lebih awet.",
    cat: "Tenda",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Design tangguh untuk dicuaca ekstrem, sangat ringan dan simpel untuk dibawa, mudan didirikan, dengan bahan nylon dan coating silicon, membuat tenda sangat ringan dan lebih awet." },
      { label: "Dimension ", value: "205x110x100cm" },

      { label: "Material ", value: "20D nylon r/s Coating Silicone, PU 5000mm.       " },
      { label: "Weight", value: "1,6 kg " },
      {
        label: "Frame ",
        value: "Alloy pole 8.5mm ",
      },
    ],
  },
  {
    _id: "213",
    img: ruban1,
    productName: "CONSINA ULTRA PEAK BOOTS TRAIL RUN",
    price: "25.000",
    color: "1 hari",
    badge: true,
    brand: "Consina",
    des: "Di desain khusus untuk sebuah pencapain sepatu trail yang ringan, lentur, sangat nyaman, tetapi tetap aman karena ankel support yang menjaga stabilitas kaki anda. Bahan yang ringan dan juga kuat dipress langsung dengan bahan membrane waterproof technology NEODry , untuk menjaga kaki anda tetap kering/anti air dan juga bernafas/breathable.",
    cat: "Sepatu",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Boots/ Sepatu ini sangat tepat digunakan bagi yang memerlukan kelincahan seperti Ultra trail/ Trail run , dan juga sangat nyaman digunakan untuk Hiking/Trekking maupun travelling ." },
      { label: "Size ", value: "38-45" },

      { label: "Material ", value: "Poly strong Mesh, Rubber Outsole grip, Neodry technology membrane breathable / waterproof " },
      { label: "Weight", value: "600 gram " },
      {
        label: "Gender ",
        value: "Pria & Wanita ",
      },
    ],
  },
  {
    _id: "214",
    img: ruban2,
    productName: "CONSINA HIKER PRO",
    price: "25.000",
    color: "1 hari",
    badge: true,
    brand: "Consina",
    des: "Sepatu Hiking/Trekking terbaik yang sangat nyaman digunakan . Karena menggunakan bahan kulit premium yang sangat lentur dan bantalan tapak kaki yang empuk juga adanya ankel support . Sehingga perjalanan anda lebih Aman. Menggunakan membrane premium, sehingga menjaga boots tetap kering/waterproof tetapi tetap bernafas/breathable .",
    cat: "Sepatu",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Light, durable, tough,comfort, waterproof , breathable ." },
      { label: "Size ", value: "38-45" },

      { label: "Material ", value: "Kulit suede premium       " },
      { label: "Weight", value: "580 gram " },
      {
        label: "Gender ",
        value: "untuk Pria & Wanita ",
      },
    ],
  },

  {
    _id: "217",
    img: bac1,
    productName: "EIGER MUMMY 250 SLEEPING BAG",
    price: "35.000",
    color: "1 hari",
    badge: true,
    brand: "Eiger",
    des: "Sleeping bag Mummy 250 di desain untuk memberikan kenyamanan ketika digunakan pada saat tidur. Mampu menjaga suhu tubuh tetap normal sekaligus menghangatkan tubuh dari cuaca dingin ketika berada di hutan atau gunung. Pemakaian optimal dalam suhu 0-15 derajat celcius. Tinggi maksimal 180 cm.",
    cat: "Sleeping Bag",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Mampu menjaga suhu tubuh tetap normal sekaligus menghangatkan tubuh dari cuaca dingin ketika berada di hutan atau gunung." },
      { label: "Dimension ", value: "220 x 75 x 50 cm" },

      { label: "Material ", value: "Polyester Ripstop + Dacron       " },
      { label: "Weight", value: "1 kg " },
      {
        label: "Gender ",
        value: "untuk Pria & Wanita ",
      },
    ],
  },
  {
    _id: "219",
    img: bac2,
    productName: "EIGER RECT PILOT 250 US SLEEPING BAG",
    price: "220.00",
    color: "Black",
    badge: true,
    brand: "Eiger",
    des: "Sleeping bag Rect Pilot 250 US di desain untuk memberikan kenyamanan ketika digunakan pada saat tidur. Mampu menjaga suhu tubuh tetap normal sekaligus menghangatkan tubuh dari cuaca dingin ketika berada di hutan atau gunung. Pemakaian optimal dalam suhu 10-15 derajat celcius.",
    cat: "Sleeping Bag",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Oversized top draft tube, Heat-trap collar with surf leash closure, Ground-level zipper" },
      { label: "Dimension ", value: "220 x 75 x 50 cm" },

      { label: "Material ", value: "Polyester Honeycomb 70D W/R Cire.       " },
      { label: "Weight", value: " 950 gram " },
      {
        label: "Gender ",
        value: "untuk Pria & Wanita ",
      },
    ],
  },

  // =================== imprimante hp =================

  {
    _id: "hp1",
    img: hp1,
    productName: "CONSINA CARRIER CENTURION 50L",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Consina",
    des: "Desc : Consina Centurion adalah carrier berkapasitas 45 liter yang dirancang untuk kegiatan hiking singkat, yakni 1-2 hari. Kompartemen utama tas ini dapat diakses dengan mudah melalui bukaan atas. Di dalam saku tutup atas, terdapat saku di bagian dalam untuk menyimpan barang-barang yang lebih kecil. Tas ini juga memiliki dua saku samping sebagai tempat penyimpanan tambahan. Teknologi Fit Light Hike Backsystem pada tas ini berfungsi untuk memberikan kenyamanan saat melakukan kegiatan hiking dengan menyediakan sirkulasi udara yang lebih baik. Tas ini dilengkapi juga dengan fitur-fitur lain untuk mendukung kegiatan hiking Anda seperti pengikat trekking pole, tali kompresi samping, hip belt, dan tali dada dengan peluit.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Fit Light adalah teknologi backsystem yang dirancang ringan dan ringkas untuk kebutuhan pergerakan yang cepat saat melakukan kegiatan summit attack (perjalanan penuntas menuju puncak)." },
      { label: "Dimension ", value: "55 x 30 x 20 cm" },

      { label: "Material ", value: "CANVAS BACK P/900D     " },
      { label: "Load Range", value: "2-7kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },

  
  // =================== imprimante ricoh =================
  {
    _id: "ricoh1",
    img: ricoh1,
    productName: "OSPREY AURA AG LT 65 S23 CARRIER",
    price: "100.000",
    color: "1 hari",
    badge: true,
    brand: "Osprey",
    des: "Saat perjalanan membutuhkan tas yang ringan namun Anda tidak bisa berkompromi dengan kenyamanan dan daya angkut, Aura AG LT 65 yang ramping menawarkan yang terbaik dari keduanya. Dari akhir pekan yang penuh dengan perlengkapan hingga ekspedisi pedalaman terlama Anda, LT menghadirkan suspensi AntiGravity pemenang penghargaan yang sama sambil menyediakan serangkaian fitur yang bijaksana, efisien, dan mumpuni. Kami memangkas bobot sesuai kebutuhan sambil mempertimbangkan fitur inti yang menjadikan Aura andalan: penutup hujan terintegrasi, akses ritsleting panel samping, tutup atas mengambang, saku dorong yang diperkuat, dan selongsong hidrasi internal. Dibuat dengan kain bodi utama daur ulang yang disetujui bluesign dan dirancang untuk melewati ujian waktu, ke mana pun Anda membawanya.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Included raincover made with PFC/PFAS-free DWR and bluesign approved materials, Curved zip access on one side of panel, Fabric reinforced front shove-it pocket." },
      { label: "Dimension ", value: "78H x 40W x 30D cm" },

      { label: "Material ", value: "bluesign approved recycled 210D nylon honey comb contrast, PFAS-free DWR     " },
      { label: "Load Range", value: "10-20kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },

  {
    _id: "ricoh2",
    img: ricoh2,
    productName: "OSPREY ATMOS AG LT 65 S23 CARRIER",
    price: "100.000",
    color: "1 hari",
    badge: true,
    brand: "Osprey",
    des: "Saat perjalanan membutuhkan paket yang ringan namun Anda tidak bisa berkompromi dengan kenyamanan dan daya angkut, Atmos AG LT 65 yang ramping membuktikan bahwa keduanya dapat dioptimalkan. Dari akhir pekan yang penuh dengan perlengkapan hingga ekspedisi pedalaman terlama Anda, LT menghadirkan suspensi AntiGravity yang memeluk tubuh sekaligus memberikan serangkaian fitur yang bijaksana, ramping, dan mumpuni. Kami memangkas bobot di tempat yang penting sambil mempertimbangkan fitur inti yang membuat Atmos begitu serbaguna: penutup hujan terintegrasi, akses ritsleting panel samping, tutup atas mengambang, saku dorong yang diperkuat, dan selongsong hidrasi internal. Dibuat dengan kain bodi utama daur ulang yang disetujui bluesign® dan dirancang untuk melewati ujian waktu, ke mana pun Anda membawanya.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Included raincover made with PFC/PFAS-free DWR and bluesign® approved materials, Curved zip access on one side of panel, Fabric reinforced front shove-it pocket, Tall dual-access side water bottle pockets, Dual upper/lower side compression straps, Dual zippered hipbelt pockets." },
      { label: "Dimension ", value: "85 x 39 x 32 cm" },

      { label: "Material ", value: "MAIN: bluesign approved recycled 210D nylon honey comb contrast, PFAS-free DWR, ACCENT: bluesign approved recycled 210D high tenacity nylon, PFAS-free DWR    " },
      { label: "Load Range", value: "10-20kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },
  {
    _id: "ricoh3",
    img: ricoh3,
    productName: "OSPREY VOLT 65 F22 CARRIER",
    price: "100.000",
    color: "1 hari",
    badge: true,
    brand: "Osprey",
    des: "Berikan energi pada pengalaman backpacking Anda dengan Volt 65, dibuat untuk mereka yang mengharapkan kesesuaian dan kenyamanan luar biasa namun mendambakan desain yang sederhana dan bersih. Sangat dapat disesuaikan, Volt 65 adalah pekerja keras bergaya ransel, siap untuk melakukan perjalanan semalaman di akhir pekan hingga seminggu, bahkan ketika barang bawaan Anda menjadi berat. Suspensi AirScape-nya memberikan kesesuaian yang dekat dengan tubuh, bernapas, dan stabil yang menanggung beban Anda. Siap untuk apa pun yang Anda inginkan dalam perjalanan, Volt dilengkapi penutup hujan, kantong botol jaring samping yang mudah diakses, selongsong internal untuk wadah hidrasi, dan berbagai titik pemasangan untuk meningkatkan kemampuan membawa Anda. Ditambah lagi, produk ini dibuat secara berkelanjutan dengan 100% bahan daur ulang.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Included raincover made with PFC/PFAS-free DWR and bluesign approved materials, Dual zippered hipbelt pockets, Internal hydration sleeve with hose port in backpanel, Dual side compression straps, Dual ice axe/trekking pole loops, Front panel lash loops for attaching extra gear, Accessory pad straps." },
      { label: "Dimension ", value: "78H x 38W x 26D cm" },

      { label: "Material ", value: "MAIN: Bluesign approved 600D recycled polyester, PFC/PFAS-free DWR, ACCENT: Bluesign approved 450D recycled polyester, PFC/PFAS-free DWR     " },
      { label: "Load Range", value: "10-20kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },
  {
    _id: "ricoh4",
    img: ricoh4,
    productName: "OSPREY KESTREL 48 S23 CARRIER",
    price: "85.000",
    color: "1 hari",
    badge: true,
    brand: "Osprey",
    des: "Jika Anda membutuhkan paket yang dapat menangani gesekan melalui ngarai batu pasir, mendaki puncak yang tertutup salju, atau mengangkut perlengkapan Anda untuk seharian bekerja di jalan setapak, Kestrel dapat mengatur semua itu dan banyak lagi. Untuk akhir pekan yang ringan atau hari-hari besar, Kestrel 48 liter adalah tas bergaya ransel yang dibuat untuk mengangkut peralatan berat melalui lingkungan yang menantang.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Included raincover made with bluesign approved fabrics and DWR treatments made without PFAS, stored in zippered pocket at base of pack, Top lid with large, zippered pocket; top panel lash points and under lid zippered mesh pocket with key clip." },
      { label: "Dimension ", value: "74H x 40W x 30D cm" },

      { label: "Material ", value: "MAIN: bluesign approved 100% recycled 420D nylon, DWR treatments made without PFAS, ACCENT: bluesign approved 100% recycled 500D high-tenacity nylon, DWR treatments made without PFAS" },
      { label: "Load Range", value: "2-7kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  
  },

  // =================== imprimante ricoh =================

  {
    _id: "espson1",
    img: espson1,
    productName: "AREI PREMIUM CARRIER MANDALA 60L",
    price: "50.000",
    color: "1 hari",
    badge: true,
    brand: "Arei",
    des: "Tas Gunung / Carrier Premium Mandala 60 Liter Arei Outdoorgear dirancang untuk kegiatan Pendakian selama 3-4 hari. Dilengkapi kompartement utama dan kompartement tambahan seperti saku depan, organizer, saku samping, dan raincover. Carrier juga merupakan Carrier ini merupakan carrier Premium dengan yang beratnya sangat ringan, hingga membuat Arengers sangat Nyaman ketika Menggunakkannya.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Compression Straps, Stabilizer Straps, Sternum Strap With Whistle, Rain Cover." },
      { label: "Dimension ", value: " 60 x 37 x 23 cm" },

      { label: "Material ", value: "Polyester     " },
      { label: "Load Range", value: "5-15kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },

  {
    _id: "espson2",
    img: espson2,
    productName: "AREI SEMI CARRIER KELIMUTU 40L",
    price: "35.000",
    color: "1 hari",
    badge: true,
    brand: "Arei",
    des: "Tas Ransel atau Semi Carrier Kelimutu 40 Liter Arei Outdoorgear dirancang untuk kegiatan hiking ringan selama 1-2 hari. Dilengkapi kompartement utama dan kompartement tambahan seperti saku depan, organizer, dan saku samping serta sudah Water Repellent. Semi Carrier Kelimutu 40 Liter siap menemani Petualangan Areingers.",
    cat: "Carrier",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Lubang Water Blader, Hose Holder, Tracking Pole Loops, Sternum Strap with Whistle, Hip Belt." },
      { label: "Dimension ", value: "52 x 26 x 17 cm" },

      { label: "Material ", value: "Polyester     " },
      { label: "Load Range", value: "3-10kg " },
      {
        label: "Gender ",
        value: "untuk Pria ",
      },
    ],
  },
];
